source run_POGTightroch_corrected_DoubleMuon.sh
source run_HNTightroch_corrected_DoubleMuon.sh
source run_POGTight_DoubleEG.sh
source run_POGTighttruthmatch_DoubleEG.sh
source run_POGTightroch_corrected_SingleMuon.sh
source run_POGTightroch_corrected_SingleElectron.sh
source run_POGTighttruthmatch_SingleElectron.sh