# $Id: Makefile
###########################################################################                                                                                                    
# @Project: LQAnalyzer - ROOT-based analysis framework for Korea CMS      #                                                                                                    
#                                                                         #                                                                                                    
# @author John Almond       jalmond@cern.ch>           - SNU              #                                                                                                    
# Top level Makefile for compiling all the LQAnalyzer code                #                                                                                                    
#                                                                         #                                                                                                    
###########################################################################                                                                                                    


# Package information
LIBRARY = Ntuplecore80X
OBJDIR  = $(OBJ)
DEPDIR  = $(OBJDIR)/dep
SRCDIR  = src
INCDIR  = include

include $(LQANALYZER_DIR)/bin/Make/Makefile.common