# Package information
LIBRARY = Plotting94X
OBJDIR  = $(OBJ)
DEPDIR  = $(OBJDIR)/dep
SRCDIR  = src
INCDIR  = include

# Include the generic compilation rules
include $(LQANALYZER_DIR)/bin/Make/Makefile.common

INCLUDES += -I$(LQANALYZER_DIR)/LQCore/94X/Ntuplecore/include/
