# Package information
LIBRARY = AnalysisCore
OBJDIR  = obj
DEPDIR  = $(OBJDIR)/dep
SRCDIR  = src
INCDIR  = include


# Include the generic compilation rules
include $(LQANALYZER_DIR)/Makefile.common

#INCLUDES += -I$(LQANALYZER_DIR)/SNUTree/include/


