# Package information
LIBRARY = LQCycle
OBJDIR  = obj
DEPDIR  = $(OBJDIR)/dep
SRCDIR  = src
INCDIR  = include

# Include the generic compilation rules
include $(LQANALYZER_DIR)/Makefile.common

INCLUDES += -I$(LQANALYZER_DIR)/SNUTree/include/
INCLUDES += -I$(LQANALYZER_DIR)/LQCore/core/include/
INCLUDES += -I$(LQANALYZER_DIR)/LQCore/Selection/include/
INCLUDES += -I$(LQANALYZER_DIR)/LQCore/Plotting/include/
