# $Id: Makefile
###########################################################################                                                                                                    
# @Project: LQAnalyzer - ROOT-based analysis framework for Korea CMS      #                                                                                                    
#                                                                         #                                                                                                    
# @author John Almond       jalmond@cern.ch>           - SNU              #                                                                                                    
# Top level Makefile for compiling all the LQAnalyzer code                #                                                                                                    
#                                                                         #                                                                                                    
###########################################################################                                                                                                    


# Package information
LIBRARY = Ntuplecore
OBJDIR  = $(OBJ)
DEPDIR  = $(OBJDIR)/dep
SRCDIR  = src
INCDIR  = include


# Include the generic compilation rules
include $(LQANALYZER_DIR)/Makefile.common
