/********************************************************************
* src/AnalysisCore_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/AnalysisCore_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableAnalysisCore_Dict();
extern void G__cpp_setup_inheritanceAnalysisCore_Dict();
extern void G__cpp_setup_typetableAnalysisCore_Dict();
extern void G__cpp_setup_memvarAnalysisCore_Dict();
extern void G__cpp_setup_globalAnalysisCore_Dict();
extern void G__cpp_setup_memfuncAnalysisCore_Dict();
extern void G__cpp_setup_funcAnalysisCore_Dict();
extern void G__set_cpp_environmentAnalysisCore_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/Reweight.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__AnalysisCore_DictLN_TDirectory;
extern G__linked_taginfo G__AnalysisCore_DictLN_TString;
extern G__linked_taginfo G__AnalysisCore_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__AnalysisCore_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__AnalysisCore_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__AnalysisCore_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__AnalysisCore_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__AnalysisCore_DictLN_TFile;
extern G__linked_taginfo G__AnalysisCore_DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__AnalysisCore_DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__AnalysisCore_DictLN_TH1D;
extern G__linked_taginfo G__AnalysisCore_DictLN_Reweight;

/* STUB derived class for protected member access */
