//
// File generated by /programs/root/bin/rootcint at Tue Nov 19 02:38:41 2013

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME srcdIAnalysisCore_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "AnalysisCore_Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::Reweight Reweight;
      #else
      class Reweight  {
         public:
         //friend XX;
         ::TFile* fileData_; //
         ::TH1D* h_MCmod_; //
         ::TH1D* h_Data_; //
      };
      #endif

   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void Reweight_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void Reweight_Dictionary();
   static void delete_Reweight(void *p);
   static void deleteArray_Reweight(void *p);
   static void destruct_Reweight(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::Reweight*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::Reweight) == sizeof(::ROOT::Shadow::Reweight));
      ::Reweight *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::Reweight),0);
      static ::ROOT::TGenericClassInfo 
         instance("Reweight", "./include/Reweight.h", 12,
                  typeid(::Reweight), DefineBehavior(ptr, ptr),
                  &Reweight_ShowMembers, &Reweight_Dictionary, isa_proxy, 4,
                  sizeof(::Reweight) );
      instance.SetDelete(&delete_Reweight);
      instance.SetDeleteArray(&deleteArray_Reweight);
      instance.SetDestructor(&destruct_Reweight);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::Reweight*)
   {
      return GenerateInitInstanceLocal((::Reweight*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::Reweight*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void Reweight_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::Reweight*)0x0)->GetClass();
   }

} // end of namespace ROOT

//______________________________________________________________________________
namespace ROOT {
   void Reweight_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class Reweight.
      typedef ::ROOT::Shadow::Reweight ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOT::GenerateInitInstanceLocal((const ::Reweight*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fileData_", &sobj->fileData_);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*h_MCmod_", &sobj->h_MCmod_);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*h_Data_", &sobj->h_Data_);
   }

}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_Reweight(void *p) {
      delete ((::Reweight*)p);
   }
   static void deleteArray_Reweight(void *p) {
      delete [] ((::Reweight*)p);
   }
   static void destruct_Reweight(void *p) {
      typedef ::Reweight current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::Reweight

/********************************************************
* src/AnalysisCore_Dict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableAnalysisCore_Dict();

extern "C" void G__set_cpp_environmentAnalysisCore_Dict() {
  G__cpp_reset_tagtableAnalysisCore_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevAnalysisCore_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* Reweight */
static int G__AnalysisCore_Dict_256_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Reweight* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new Reweight(*((TString*) G__int(libp->para[0])));
   } else {
     p = new((void*) gvp) Reweight(*((TString*) G__int(libp->para[0])));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__AnalysisCore_DictLN_Reweight));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnalysisCore_Dict_256_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((Reweight*) G__getstructoffset())->GetWeight((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnalysisCore_Dict_256_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const Reweight*) G__getstructoffset())->getTemporaryDirectory());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__AnalysisCore_Dict_256_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   Reweight* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new Reweight(*(Reweight*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__AnalysisCore_DictLN_Reweight));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef Reweight G__TReweight;
static int G__AnalysisCore_Dict_256_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (Reweight*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((Reweight*) (soff+(sizeof(Reweight)*i)))->~G__TReweight();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (Reweight*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((Reweight*) (soff))->~G__TReweight();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__AnalysisCore_Dict_256_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Reweight* dest = (Reweight*) G__getstructoffset();
   *dest = *(Reweight*) libp->para[0].ref;
   const Reweight& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* Reweight */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncAnalysisCore_Dict {
 public:
  G__Sizep2memfuncAnalysisCore_Dict(): p(&G__Sizep2memfuncAnalysisCore_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncAnalysisCore_Dict::*p)();
};

size_t G__get_sizep2memfuncAnalysisCore_Dict()
{
  G__Sizep2memfuncAnalysisCore_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceAnalysisCore_Dict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableAnalysisCore_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__AnalysisCore_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__AnalysisCore_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AnalysisCore_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__AnalysisCore_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AnalysisCore_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__AnalysisCore_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__AnalysisCore_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AnalysisCore_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__AnalysisCore_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AnalysisCore_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__AnalysisCore_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__AnalysisCore_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__AnalysisCore_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__AnalysisCore_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__AnalysisCore_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__AnalysisCore_DictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__AnalysisCore_DictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* Reweight */
static void G__setup_memvarReweight(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__AnalysisCore_DictLN_Reweight));
   { Reweight *p; p=(Reweight*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__AnalysisCore_DictLN_TFile),-1,-1,4,"fileData_=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__AnalysisCore_DictLN_TH1D),-1,-1,4,"h_MCmod_=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__AnalysisCore_DictLN_TH1D),-1,-1,4,"h_Data_=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarAnalysisCore_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncReweight(void) {
   /* Reweight */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__AnalysisCore_DictLN_Reweight));
   G__memfunc_setup("Reweight",831,G__AnalysisCore_Dict_256_0_1, 105, G__get_linked_tagnum(&G__AnalysisCore_DictLN_Reweight), -1, 0, 1, 1, 1, 0, "u 'TString' - 0 - filename", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetWeight",904,G__AnalysisCore_Dict_256_0_2, 100, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - nvtx", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getTemporaryDirectory",2232,G__AnalysisCore_Dict_256_0_3, 85, G__get_linked_tagnum(&G__AnalysisCore_DictLN_TDirectory), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("Reweight", 831, G__AnalysisCore_Dict_256_0_4, (int) ('i'), G__get_linked_tagnum(&G__AnalysisCore_DictLN_Reweight), -1, 0, 1, 1, 1, 0, "u 'Reweight' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~Reweight", 957, G__AnalysisCore_Dict_256_0_5, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__AnalysisCore_Dict_256_0_6, (int) ('u'), G__get_linked_tagnum(&G__AnalysisCore_DictLN_Reweight), -1, 1, 1, 1, 1, 0, "u 'Reweight' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncAnalysisCore_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalAnalysisCore_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcAnalysisCore_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__AnalysisCore_DictLN_TDirectory = { "TDirectory" , 99 , -1 };
G__linked_taginfo G__AnalysisCore_DictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__AnalysisCore_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__AnalysisCore_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__AnalysisCore_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__AnalysisCore_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__AnalysisCore_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__AnalysisCore_DictLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G__AnalysisCore_DictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__AnalysisCore_DictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__AnalysisCore_DictLN_TH1D = { "TH1D" , 99 , -1 };
G__linked_taginfo G__AnalysisCore_DictLN_Reweight = { "Reweight" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableAnalysisCore_Dict() {
  G__AnalysisCore_DictLN_TDirectory.tagnum = -1 ;
  G__AnalysisCore_DictLN_TString.tagnum = -1 ;
  G__AnalysisCore_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__AnalysisCore_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__AnalysisCore_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__AnalysisCore_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__AnalysisCore_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__AnalysisCore_DictLN_TFile.tagnum = -1 ;
  G__AnalysisCore_DictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__AnalysisCore_DictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__AnalysisCore_DictLN_TH1D.tagnum = -1 ;
  G__AnalysisCore_DictLN_Reweight.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableAnalysisCore_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__AnalysisCore_DictLN_TDirectory);
   G__get_linked_tagnum_fwd(&G__AnalysisCore_DictLN_TString);
   G__get_linked_tagnum_fwd(&G__AnalysisCore_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__AnalysisCore_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__AnalysisCore_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__AnalysisCore_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__AnalysisCore_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__AnalysisCore_DictLN_TFile);
   G__get_linked_tagnum_fwd(&G__AnalysisCore_DictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__AnalysisCore_DictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__AnalysisCore_DictLN_TH1D);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__AnalysisCore_DictLN_Reweight),sizeof(Reweight),-1,295936,(char*)NULL,G__setup_memvarReweight,G__setup_memfuncReweight);
}
extern "C" void G__cpp_setupAnalysisCore_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupAnalysisCore_Dict()");
  G__set_cpp_environmentAnalysisCore_Dict();
  G__cpp_setup_tagtableAnalysisCore_Dict();

  G__cpp_setup_inheritanceAnalysisCore_Dict();

  G__cpp_setup_typetableAnalysisCore_Dict();

  G__cpp_setup_memvarAnalysisCore_Dict();

  G__cpp_setup_memfuncAnalysisCore_Dict();
  G__cpp_setup_globalAnalysisCore_Dict();
  G__cpp_setup_funcAnalysisCore_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncAnalysisCore_Dict();
  return;
}
class G__cpp_setup_initAnalysisCore_Dict {
  public:
    G__cpp_setup_initAnalysisCore_Dict() { G__add_setup_func("AnalysisCore_Dict",(G__incsetup)(&G__cpp_setupAnalysisCore_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initAnalysisCore_Dict() { G__remove_setup_func("AnalysisCore_Dict"); }
};
G__cpp_setup_initAnalysisCore_Dict G__cpp_setup_initializerAnalysisCore_Dict;

