# Package information
LIBRARY = Selection
OBJDIR  = $(OBJ)
DEPDIR  = $(OBJDIR)/dep
SRCDIR  = src
INCDIR  = include

# Include the generic compilation rules
include $(LQANALYZER_DIR)/Makefile.common

INCLUDES += -I$(LQANALYZER_DIR)/LQCore/SKTree/include/
INCLUDES += -I$(LQANALYZER_DIR)/LQCore/AnalysisCore/include/
INCLUDES += -I$(LQANALYZER_DIR)/LQCore/Ntuplecore/include/
